### ISSUE TITLE
Consider changing deck source formats?

### ISSUE THREAD

**Issue by langfield** [cutthroat78/My-Sentence-Mining-Anki-Decks#1]
**Disclaimer.** This is a shameless plug for my own tool.

I've noticed this one of only a handful of Anki decks under version control, which is awesome! I hope more folks move to this model for maintaining their decks. I was wondering if you'd consider moving your deck sources over to a slightly different format?

I've build a [`git`-compatible version control tool](https://github.com/langfield/ki) for Anki decks, and I'm looking to recruit active deck maintainers to get new users and understand what needs to be improved. Let me know if you're interested!

Just to give you an idea what it's like, here's an example note source file from my project `README`:

```markdown
## Note
nid: 1655372139959
model: iKnow! Sentences
tags: 
markdown: false

### Expression
あなたが来るのを<b>待っています</b>。

### Meaning
I am waiting for you to come.
待つ -- wait, wait for

### Reading
あなた が くる の を <b>まって います</b>

### Audio
[sound:93014972e589032cfbeb9fba06bdecc6.mp3]

### Image_URI
<img src="346bb608be872c9066e8235cbf362327.jpg">

### iKnowID
sentence:247167

### iKnowType
sentence
```

**Comment by cutthroat78** [comment]
Thank you for this, but I am not interested in this tool. Personally, I feel that CSV suits me perfectly for my decks and that this tool will just add an extra layer that feels unnecessary. I hope you find maintainers and your project does well.

Also, you posted this issue on one of my less important anki deck repos. My more important anki deck repos are the other repos in [this star list](https://github.com/stars/cutthroat78/lists/my-language-anki-decks)

**Comment by langfield** [comment]
No worries, thanks for taking the time to reply!
